[package]
name = "tooth-engine"
version = "0.1.0"
authors = ["x10A94 <hyperpone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug = []

[build-dependencies]
image = "0.23"
lz4 = "1.23"
